services:
  yolo:
    build:
      context: ./yolo-service
      dockerfile: Dockerfile
    container_name: traffic_yolo
    restart: unless-stopped
    ports:
      - "0.0.0.0:8001:8001"
    volumes:
      - ./backend/models:/app/models:ro
    environment:
      - TORCH_FORCE_WEIGHTS_ONLY_LOAD=0
    env_file:
      - ./yolo-service/.env
    networks:
      - traffic_net

networks:
  traffic_net:
    driver: bridge
